# Directory paths
input_dir: "/home/isilon/HumGenAnalysis/M2/01_vali_pipe/01_data/FinaleDB/03_bam_temp"
filter_dir: "/home/isilon/HumGenAnalysis/M2/01_vali_pipe/01_data/FinaleDB/04_filter_bam"
downsample_dir: "/home/isilon/HumGenAnalysis/M2/01_vali_pipe/01_data/FinaleDB/05_downsample_bam"

# Downsampling settings
downsampling:
  threads: 4
  mem_mb: 8000
  # Map your tags to the actual number of reads
  tags:
    ds20M: 20000000
  # List of seeds to use for each sample/tag combination
  seeds:
    - 42